from __future__ import annotations

import re
from pathlib import Path

from jellyshift.config import HookConfig


def default_hook_sh(app_dir: Path, wsl_user: str) -> str:
    return f"/home/{wsl_user}/projects/JellyShift/run-hook.sh"


def sync_hook_scripts(app_dir: Path, hook: HookConfig) -> None:
    """Write hook.env and patch run-hook.cmd with current hook settings."""
    hook_sh = hook.hook_sh or default_hook_sh(app_dir, hook.wsl_user)
    write_hook_env(app_dir, hook.wsl_user)
    patch_run_hook_cmd(app_dir, hook.wsl_distro, hook.wsl_user, hook_sh)
    ensure_run_hook_sh_sources_env(app_dir)


def write_hook_env(app_dir: Path, wsl_user: str) -> None:
    env_path = app_dir / "hook.env"
    env_path.write_text(
        "# Generated by JellyShift settings — do not edit manually\n"
        f'JELLYSHIFT_DEFAULT_USER="{wsl_user}"\n',
        encoding="utf-8",
    )


def patch_run_hook_cmd(
    app_dir: Path,
    wsl_distro: str,
    wsl_user: str,
    hook_sh: str,
) -> None:
    cmd_path = app_dir / "run-hook.cmd"
    if not cmd_path.exists():
        return

    text = cmd_path.read_text(encoding="utf-8", errors="replace")
    replacements = {
        "WSL_DISTRO": wsl_distro,
        "WSL_USER": wsl_user,
        "HOOK_SH": hook_sh.replace("%WSL_USER%", wsl_user),
    }
    for key, value in replacements.items():
        text, count = re.subn(
            rf'(set\s+"{key}=)[^"]*(")',
            rf"\g<1>{value}\2",
            text,
            count=1,
            flags=re.IGNORECASE,
        )
        if count == 0:
            pass

    cmd_path.write_text(text, encoding="utf-8")


def ensure_run_hook_sh_sources_env(app_dir: Path) -> None:
    sh_path = app_dir / "run-hook.sh"
    if not sh_path.exists():
        return

    text = sh_path.read_text(encoding="utf-8")
    marker = "# JellyShift hook.env"
    if marker in text:
        return

    insert = (
        f'{marker}\n'
        '[[ -f "$APP_DIR/hook.env" ]] && source "$APP_DIR/hook.env"\n'
    )
    # APP_DIR is set after line 13; insert after APP_DIR assignment
    target = 'APP_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"\n'
    if target in text:
        text = text.replace(target, target + insert, 1)
    else:
        text = insert + text

    text = re.sub(
        r'WSL_USER="\$\{JELLYSHIFT_USER:-[^"]+\}"',
        'WSL_USER="${JELLYSHIFT_USER:-${JELLYSHIFT_DEFAULT_USER:-sharath}}"',
        text,
        count=1,
    )
    sh_path.write_text(text, encoding="utf-8")
